set(srcs "main.cpp"
         "connect_wifi.c"
         "wifiStreamTask.c"
         "cameraTask.c"
         "udpLogger.c"
         "ota_task.c"
         "c3_programmer.c"
         "update_manager.c"
         )
idf_component_register(SRCS ${srcs}
                    INCLUDE_DIRS "." "../include"
                    REQUIRES "esp-serial-flasher" 
                             "driver" 
                             "esp_lcd" 
                             "nvs_flash"
                             "esp_wifi" 
                             "esp_http_client" 
                             "esp_timer" 
                             "app_update" 
                             "esp_https_ota" 
                             "esp_http_client" 
                             "nvs_flash" 
                             "lwip" 
                             "esp_wifi" 
                             "esp_http_server" 
                             "esp_driver_uart"
                             "Adafruit_VL53L0X"
                             "arduino-esp32"
                    EMBED_FILES "ESP-C3_Firmware.bin"
                    )