set(srcs "main.cpp"
         "vl53l0x_task.c"
         "connect_wifi.c"
         "wifiStreamTask.cpp"
         "cameraTask.c"
         "udpLogger.c"
         "ota_task.c"
         "c3_programmer.c"
         "uartTx.c"
         "c3_programmer_version.c"
         "net_discovery.c"
         )
idf_component_register(SRCS ${srcs}
                    INCLUDE_DIRS "." "../include"
                    REQUIRES "esp-serial-flasher" 
                             "driver" 
                             "esp_lcd" 
                             "nvs_flash"
                             "esp_wifi" 
                             "esp_http_client" 
                             "esp_timer" 
                             "app_update" 
                             "esp_https_ota" 
                             "esp_http_client" 
                             "nvs_flash" 
                             "lwip" 
                             "esp_wifi" 
                             "esp_http_server" 
                             "esp_driver_uart"
                             "arduino-esp32"
                             "WebSockets_Generic"
                             "esp-tls"
                             "esp_websocket_client"

                    )